openapi: "3.0.0"
info:
  version: 1.0.0
  title: Devcomb API
  license:
    name: MIT
servers:
- url: /api/
  description: The production API server
paths:
  /api/getSideNavMenus1:
    get:
      tags:
      - "SideNavMenus"
      summary: "Get Side Navigation Menu Items with URLs"
      description: ""
      operationId: "getSideNavMenus"
      responses:
        200:
          description: "successful operation"