openapi: "3.0.0"
info:
  version: 1.0.0
  title: Devcomb API
  license:
    name: MIT
servers:
- url: /{basePath}
  description: The production API server
  variables:
    basePath:
      default: v2
paths:
  /api/getSideNavMenus:
    get:
      tags:
      - "SideNavMenus"
      summary: "Get Side Navigation Menu Items with URLs"
      description: ""
      operationId: "getSideNavMenus"
      responses:
        200:
          description: "successful operation"
  /api/getSideNavMenuitemModuleURL:
    get:
      summary: Info for a specific pet
      operationId: "getSideNavMenuitemModuleURL"
      tags:
        - SideNavMenuitemModuleURL    
    parameters:
        - name: action
          in: path
          required: true
          description: The module location of the action to retrieve
          schema:
            type: string
