-   Item: "Query Ledger"
    Action: "get_ledger"
-   Item: "Put Ledger"
    Action: "put_ledger"
-   Item: "Chaincode(s)"
    Action: "chaincode"
-   Item: "Policies"
    Action: "policies"
-   Item: "Certs"
    Action: "certs"
-   Item: "Users"
    Action: "users"

